version: '3'

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./frontend/dist:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - nestjs

  php:
    image: webdevops/php-apache-dev:8.2
    volumes:
      - ./php-app:/app
    ports:
      - "8001:80"
    environment:
      WEB_DOCUMENT_ROOT: /app/public

  django:
    build:
      context: ./django  # Путь к папке с проектом Django
      dockerfile: Dockerfile  # Путь к файлу Dockerfile
    ports:
      - "8002:8000"  # Проброс портов (локальный порт:порт контейнера)
    volumes:
      - ./django:/code  # Монтирование локальной директории в контейнер
    command: python manage.py runserver 0.0.0.0:8000  # Команда для запуска Django сервера

  nestjs:  # Добавляем сервис для Nest.js
    image: node:alpine  # Используем образ Node.js из Docker Hub
    ports:
      - "8003:3000"
    volumes:
      - ./node-app/nest-app:/usr/src/app  # Монтируем код Nest.js в контейнер
    working_dir: /usr/src/app  # Устанавливаем рабочий каталог
    command: npm start  # Команда для запуска приложения Nest.js
